IF OBJECT_ID('dbo.exec_sum_customer_profit', 'U') IS NOT NULL 
DROP TABLE dbo.exec_sum_customer_profit
GO 

SELECT * INTO exec_sum_customer_profit FROM (

SELECT 
    YEAR(POSISI) year, 
    MONTH(POSISI) month,
	DIV_ID division,
    SUM(ISNULL(LABA_RUGI_FTP_SETELAH_MODAL,0)) setelah_modal
FROM FACT_SUMMARY_LABA_RUGI
INNER JOIN VIEW_CUSTOMER_MAPPING ON 
FACT_SUMMARY_LABA_RUGI.CIFNO = VIEW_CUSTOMER_MAPPING.CIF
WHERE DIV_ID IS NOT NULL
GROUP BY YEAR(POSISI), MONTH(POSISI), DIV_ID
) SOURCE;