IF OBJECT_ID('dbo.summary_top_bottom', 'U') IS NOT NULL 
DROP TABLE dbo.summary_top_bottom
GO 

select * into summary_top_bottom from (

SELECT 

LABARUGI_SUM.YEAR  year , 
LABARUGI_SUM.MONTH month,
VIEW_CUSTOMER_MAPPING.div_id        division,  
VIEW_CUSTOMER_MAPPING.company_name  nama_nasabah,  
VIEW_CUSTOMER_MAPPING.vcif          vcif        , 

SUM(ISNULL(LABARUGI_SUM.JUMLAH,0))   jumlah,
SUM(ISNULL(KREDIT_SUM.KREDIT,0))     kredit , 
SUM(ISNULL(SIMPANAN_SUM.SIMPANAN,0)) simpanan

FROM (
	SELECT 
		YEAR(POSISI) YEAR,
		MONTH(POSISI) MONTH,
		CIFNO, 
		SUM(ISNULL(LABA_RUGI_FTP_SETELAH_MODAL,0)) jumlah
	FROM FACT_SUMMARY_LABA_RUGI
	GROUP BY YEAR(POSISI), MONTH(POSISI), CIFNO
)LABARUGI_SUM

INNER JOIN VIEW_CUSTOMER_MAPPING 
ON LABARUGI_SUM.CIFNO = VIEW_CUSTOMER_MAPPING.CIF 
AND VIEW_CUSTOMER_MAPPING.VCIF IS NOT NULL
AND VIEW_CUSTOMER_MAPPING.DIV_ID IS NOT NULL

LEFT JOIN (
	SELECT 
		YEAR(POSISI) YEAR,
		MONTH(POSISI) MONTH,
		CIFNO, 
		SUM(ISNULL(AVRGSALDO,0)) simpanan
	FROM FACT_SIMPANAN_CPA
	GROUP BY YEAR(POSISI), MONTH(POSISI), CIFNO
)SIMPANAN_SUM
ON LABARUGI_SUM.YEAR = SIMPANAN_SUM.YEAR
AND LABARUGI_SUM.MONTH = SIMPANAN_SUM.MONTH
AND LABARUGI_SUM.CIFNO = SIMPANAN_SUM.CIFNO

LEFT JOIN (
	SELECT 
		YEAR(POSISI) YEAR,
		MONTH(POSISI) MONTH,
		CIFNO, 
		SUM(ISNULL(BAKI_DEBET_RATAS,0)) kredit
	FROM FACT_KREDIT_CPA
	GROUP BY YEAR(POSISI), MONTH(POSISI), CIFNO
)KREDIT_SUM
ON LABARUGI_SUM.YEAR = KREDIT_SUM.YEAR
AND LABARUGI_SUM.MONTH = KREDIT_SUM.MONTH
AND LABARUGI_SUM.CIFNO = KREDIT_SUM.CIFNO

GROUP BY
	LABARUGI_SUM.YEAR, 
	LABARUGI_SUM.MONTH,
	VIEW_CUSTOMER_MAPPING.div_id,
	VIEW_CUSTOMER_MAPPING.company_name,
	VIEW_CUSTOMER_MAPPING.vcif
	
)source;